### PR TITLE
Associating an Object to IDiscordClient

### PR DESCRIPTION
**Pull request by danthonywalker**
### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [ ] I have tested this feature thoroughly
  * I have not tested this, however, it does compile completely. If someone wishes to check if the Object can be retrieved/set correctly than that'd be fine, but I don't think it's entirely necessary.

**Issues Fixed:** This change provides 2 big benefits.
1. Can alleviate the need to use a [singleton pattern](https://stackoverflow.com/questions/137975/what-is-so-bad-about-singletons) to access the "client manager". A lot of bot developers usually have a singleton class that they can access, usually from Events, to get more data about the application itself. By associating the class with the client, that would no longer be required.

2. Modules would be able to assume more data about the client and function more flexibly. For example, modules can provide an interface that the aforementioned client managers can implement and if they associate that client manager than the module can utilize that data.

### Changes Proposed in this Pull Request
* Able to store and retrieve an arbitrary object from IDiscordClient.
* Able to build the client initially with said object.

### CODE REVIEW

**Comment by austinv11** [comment]
I personally believe this is out of the scope of D4J, but I am leaving this open for more public review

**Comment by danthonywalker** [comment]
For the first point maybe, but I believe modules benefiting falls in scope. I think the benefit of modules knowing more from the user without the user needing to call a module-specific method/class is a good one. It gives it a more SPI approach.

**Comment by ArsenArsen** [comment]
Modules fall out of scope too

**Comment by austinv11** [comment]
If this were to be accepted, it cannot be a generic object singleton. Else it would be too easy to override between modules. It would have to be `Map<String, Object>` so that data can follow the pattern of namespace, data pairs to prevent collisions

**Comment by danthonywalker** [comment]
It would require the user to know a non-type-safe module-specific namespace though (unless it's enforced through something like the module's name). Another suggestion is that the data must be final (so set during construction) for the overriding problem.

**Comment by austinv11** [comment]
Well, then how would it be mutated to being with? because the module system encourages launching D4J as a standalone jar which means that D4J creates the client instance, not allowing any further mutation by modules. And regardless of the impl this will by non-type-safe. It's simply unavoidable due to the nature of what you are doing.

**Comment by danthonywalker** [comment]
Well the idea is the module (optionally) has an interface that the user implements. When the module is enabled it can check if the client is holding an instance of that interface (can throw an exception otherwise). With the map approach it's not only the interface the user has to worry about but the naming of the key and every retrieval would have to provide said key.

**Comment by austinv11** [comment]
But if the user is implementing a module specific interface why not go one step further and call a method on the module to tell it directly about that interface?

**Comment by danthonywalker** [comment]
I may be misunderstanding what you mean. What do you mean by "call a method on the module to tell it directly about that interface"?

**Comment by austinv11** [comment]
I mean make your module have a method to register or do whatever you're trying to do indirectly by having the module detect an interface.

**Comment by danthonywalker** [comment]
Since PR #323  incorporates this idea better (and I also fucked up commits) I'm going to close this PR so I can work on other stuff on the dev branch

**Pull request closed without merging**
