### PR TITLE
Removed the ellipses from gradle section so people can copy it easily

### PR DESCRIPTION
**Pull request by johnfg10**
### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [x] I have tested this feature thoroughly
  * [Proof of testing](screenshot, any evidence you tested this pull request)
I copyed it straight into my build.gradle?
**Issues Fixed:** [The issues fixed by this pull request]
Allows people to copy the gradle build settings quickly and easily 
### Changes Proposed in this Pull Request
* Removed ellipses from gradle section 

...

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
i vouch for this

**Comment by austinv11** [comment]
This is unnecessary. The sample is not intended to be a complete gradle script on its own. Additionally, it's not difficult to just copy and paste the parts of the script you actually need. Finally, this PR would make it inconsistent with the maven example.

**Comment by johnfg10** [comment]
but is it not better that people can easily copy the script into the build.gradle
no its not difficult but i know i personally have used this library in  about 5-6 projects now and removing them every time is very repetitive when they could just be removed from the repo and make mine and multiple other developers lives a little easier
also i have now done the same for the maven example(removed the ellipses) to make both examples equivalent

**Comment by austinv11** [comment]
I still don't consider this much of an issue. I personally do not consider the examples on the readme "real code" they are much closer to pseudo-code in that its purpose is to show the general concepts behind, say, using this project on gradle. This PR is also too insignificant to be accepted, it would've been better to have it as an issue (which I still wouldn't accept as a real issue).

**Pull request closed without merging**
