### PR TITLE
Improve the events system

### PR DESCRIPTION
**Pull request by waliedyassen**
### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [ ] I have tested this feature thoroughly
  * The pull was tested in a closed server bot which I am working on.

**Issues Fixed:** None

### Changes Proposed in this Pull Request
* Improves the events overall/dispatching performance.
* Adds the support for cancelling events using `event.cancel()` method or `setCancelled(boolean)` method.
* Adds the support for controlling the event execution order priority using `EventPriority` enum and `priority` attribute in `EventSubscriber)
* Expose EventHandler to public with proper documentation.

### Example
```java
@EventSubscriber(priority = EventPriority.HIGH)
public void handleCommand(MessageReceivedEvent event) {
	String content = event.getMessage().getContent();
	if (!content.startsWith("::")) {
		return;
	}
	System.out.println("Command:" + content);
	event.cancel(); 
        // calling event.cancel() will prevent this event from being passed to #handleChat handler
}

@EventSubscriber(priority = EventPriority.LOW)
public void handleChat(MessageReceivedEvent event) {
	// Command messages will never be called here, since they get cancelled in handleCommand method
	String content = event.getMessage().getContent();
	System.out.println("Chat:" + content);
}
```

### CODE REVIEW

**Comment by austinv11** [comment]
Before I review, I request that you resolve the current general issues:
1. I do not believe we should support the cancellation of events. It misrepresents how discord functions and I believe it could lead to bad code practices. 
2. What is the point of making EventHandler public?
3. If you are making the claim that this improves performance, would it be possible to get some basic benchmarks?

**Comment by waliedyassen** [comment]
## Event Cancellation
The event cancellation is an important feature in my opinion, and should be in included in all of the EventBus systems such as the one in this project, I don't see why would someone get confused about what does `cancel()` do after reading the API documentation, or even how would it lead to bad code practices, the documentation explains it pretty well.

It is necessary in many situations and let us get rid of the ugly checks you have to put in, for example if you are having a complex Discord4J bot system with multiple `MessageReceivedEvent` handler, and each handler should run under certain circumstances, such as commands one require the message to start with a specific prefix, you can just `cancel()` the event instead of letting it being passed to other handlers, that lets us avoid writing the checks or if the message is a command message in the other `MessageReceivedEvent` handlers, such as the profanity filter which may obviously censor the command content, that makes the code much more cleaner.

An example of what I am talking about:
```java
@EventSubscriber
public void handleProfanityFilter(MessageReceivedEvent event) {
    String content = event.getMessage().getContent();
    if (content.startsWith(COMMAND_PREFIX)) {
        return;
    }
    // handle filtering..
}

@EventSubscriber
public void handleCommand(MessageReceivedEvent event) {
    String content = event.getMessage().getContent();
    if (content.startsWith(COMMAND_PREFIX)) {
        // handle commands..
    }    
}
```
Keep in mind, this is only with two handlers, let alone the amount of checks necessary if you have a large bot system.

P.S People with EventBus experience will acknowledge what it does already, the rest should be reading the API documentation, which they already do I suppose.

## Exposing EventHandler
This wasn't really needed or I don't even see much people using this, the reason behind me exposing it is due to the changes I made, which required access from a different package, but at the same time, I don't see why keeping it private, exposing it would give Discord4J more flexibility and it gives Discord4J more low level API capabilities.

## Performance Improvements
### How was it done
The performance gain is mainly earned by making the iterators go through much less objects, to find or select an `EventHandler` to peform whatever we want on it, including dispatching, registering, or unregistering operations.

When we are dispatching an `Event` object, in-before, we would go through every single `EventHandler` object in the registry and do the necessary checks to see if it matches our `Event` class type or not, all the handlers were being in a single `EventHandler` registry, but after this PR, each `Event` sub-class have it's own `EventHandler` registry, so whenever we are dispatching an `Event`, we will only be looking through it's own registry, which gets rid of the unnecessary iterations and checks we had in-before.

### Benchmarks
The benchmark test was done against the dispatch method, the test dispatches 10 `ReadyEvent`s each time, the dispatcher has many `Event`s registered but not every kind that a typical large bot would use.

*Before*

```
Result "me.waliedyassen.benchmarks.Discord4JBenchmark.testDispatch":
  0.060 ±(99.9%) 0.001 ms/op [Average]
  (min, avg, max) = (0.052, 0.060, 0.065), stdev = 0.002
  CI (99.9%): [0.059, 0.060] (assumes normal distribution)


# Run complete. Total time: 00:01:56

Benchmark                        Mode  Cnt  Score   Error  Units
Discord4JBenchmark.testDispatch  avgt  100  0.060 ± 0.001  ms/op
```
---------------
*After*
```
Result "me.waliedyassen.benchmarks.Discord4JBenchmark.testDispatch":
  0.040 ±(99.9%) 0.001 ms/op [Average]
  (min, avg, max) = (0.029, 0.040, 0.052), stdev = 0.004
  CI (99.9%): [0.039, 0.041] (assumes normal distribution)


# Run complete. Total time: 00:01:57

Benchmark                        Mode  Cnt  Score   Error  Units
Discord4JBenchmark.testDispatch  avgt  100  0.040 ± 0.001  ms/op
```
P.S
1. All the benchmarks were done using `EventDispatcher` object, there was no `IDiscordClient`
2. All the tests were done using the JMH tool which is provided by the OpenJDK project.

**Comment by MinnDevelopment** [comment]
Can you show how the event handlers would be a bottleneck that needs to be optimized with this kind of system?

**Comment by MinnDevelopment** [comment]
I'd even consider your example one of the bad code practices that @austinv11 mentioned.
```java
@EventSubscriber
public void handleProfanityFilter(MessageReceivedEvent event) {
    String content = event.getMessage().getContent();
    if (content.startsWith(COMMAND_PREFIX)) {
        return;
    }
    // handle filtering..
}

@EventSubscriber
public void handleCommand(MessageReceivedEvent event) {
    String content = event.getMessage().getContent();
    if (content.startsWith(COMMAND_PREFIX)) {
        // handle commands..
    }    
}
```
Should probably be
```java
public void handleProfanityFilter(MessageReceivedEvent event) {
    String content = event.getMessage().getContent();
    // handle filtering..
}

public void handleCommand(MessageReceivedEvent event) {
    String content = event.getMessage().getContent();
    // handle commands
}

@EventSubscriber
public void handleMessage(MessageReceivedEvent event) {
    String content = event.getMessage().getContent();
    if (content.startsWith(COMMAND_PREFIX)) {
        handleCommand(event);
    } else {
        handleProfanityFilter(event);
    }
}
```

**Comment by waliedyassen** [comment]
@MinnDevelopment My example won't be a bad practice considering it will be used in a multi-module system where `handleCommand` cannot see or access `handleProfanityFilter` I think Discord4J bots are supposed to be multi-module as it recommends anyways:
> While bots aren't required to use this module system, it is recommended as it allows for multiple bots to work at the same time. 

Despite that, it is still up to the developer to do whatever they like, either using `cancel()` or using the single handler example above, in other words, adding it won't hurt but would benefit the project of more ways to do stuff, which would increase the flexibility I guess.

**Comment by MinnDevelopment** [comment]
I personally believe the proposed pattern for cancellation is not good simply due to the fact it's not very clear what handlers are executed at what point in time so you don't really know what cancel() impacts in the event chain.
When you pass around events in methods you have to make sure they don't cancel the event for you either, maybe you forget about some utility you wrote months ago that actually automatically cancels the event and then listeners suddenly stop working.

Imagine you have 5 handlers in some arbitrary order, which ones will execute if you cancel in one of them, am I missing something obvious?

>adding it won't hurt 

I disagree, this promotes bad code practice while the current restrictions of the event system promote users to construct their own handling tree for events.
I fail to see how this cancel() addition is needed in any way when event handling is hardly a bottleneck for bots, feel free to show me how it is a bottleneck for bots.

**Comment by waliedyassen** [comment]
I think you've missed the `EventPriority` enum, which controls the order of execution as the following:
```java
@EventSubscriber(priority = EventPriority.HIGH)
public void handleCommand(MessageReceivedEvent event) {
    // Should execute first, if the message is command, it will be cancelled and no longer be passed to other.
}

@EventSubscriber(priority = EventPriority.NORMAL)
public void handleOtherStuff(MessageReceivedEvent  event) {
    // Nor high or low, the default and the normal order by which methods are loaded first.
}

@EventSubscriber(priority = EventPriority.LOW)
public void handleChatLog(MessageReceivedEvent event) {
    // Should execute last and only if the event was not cancelled.
}
```
I still don't get why it would be a bad practice for someone who read the API documentation, which users are _supposedly_ to be doing anyways, it is quite handy in my opinion, but will leave the rest here now.

P.S I think you've misunderstood me, I never said it was a bottleneck, but rather said, it was an improvement to the existing one.

**Comment by MinnDevelopment** [comment]
Ok, imagine we have 5 events with the same priority. What is the order of execution?

**Comment by MinnDevelopment** [comment]
No I did not misunderstand you. The point I'm trying to make is that optimizing something that doesn't need optimization is not really important or needed.

**Comment by waliedyassen** [comment]
The order of the execution did not change for the events with the same priority, the order is controlled by which modules are loaded first and what the event methods declaration order is.

If you have 5 handlers with the same priority then that is your design issue mainly, you should know how to control the order using the `EventPriority`, having 5 handlers at `EventPriority` of `HIGH` is most likely not possible to happen.

You are right about optimizing thing that didn't really need optimization is really not needed or have that much importance, but at the same time, it will improve the efficiency of the library compared to the other Java Discord API implementation libraries, which should help in promoting the library at-least that is for me personally.

**Comment by MinnDevelopment** [comment]
The only reason I bring up the order of execution is because of your proposal for the cancellation, if you have multiple listeners it is not clear what listeners will be cancelled.
Due to there only being 3 priorities you have at max 3 buckets of events which are ordered from HIGH to LOW, however considering a bot usually has more than just 3 listeners you will definitely have more in one bucket, in this case you will not know which events would be cancelled by the call to cancel().

This would be better if the priority would be an integral rather than an enum in which case you would have full control over event execution order and could make assumptions on what cancel() would actually cancel.

**Comment by MinnDevelopment** [comment]
It makes far more sense to cancel listeners rather than events, in my honest opinion.

**Comment by waliedyassen** [comment]
I apologize If I may have been vague about what the order of the execution in my demonstration example is, the `EventPriority` can be turned into an integer which gives much more priorities range, but that is really unnecessary.

But again, that is unnecessary, at the most times, you won't need to care about the execution order except in certain places where it just an handler have to be executed before another handler, and that's just why there is only `HIGH` and `LOW` special priorities.

Despite that, I can just add more priorities such as `HIGHEST` and `LOWEST` which should most likely solve the issue you have mentioned.

You can cancel listeners the same way, the cancellation is handled at the execution of `EventHandler` so calling `cancel()` should as well cancel the execution for listeners as well.

**Comment by austinv11** [comment]
My issue with cancellation support is that in systems where cancellation exists, the framework can actually do something to cancel the effect the event has on certain components. However, in our case we are mere observers, so cancellations misrepresent what the api is actually capable of. And, in my opinion, javadocs should not be the answer to clear up this confusion as I believe apis should allow developers some sense of intuition about what they actually do before referring to docs for specificities. 

Additionally, the EventHandler was never intended for public use as there is no purpose for it. What can the EventHandler do that a user could not already do? It just pollutes the event api,

**Comment by waliedyassen** [comment]
I see, I understand the concerns about it.

**Comment by austinv11** [comment]
I am not totally against this PR though. There appears to be some performance gain and I could see event priorities being useful.

**Pull request closed without merging**
