### PR TITLE
Fix ReadyEvent not being dispatched

### PR DESCRIPTION
**Pull request by quanticc**
### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [x] I have tested this feature thoroughly

Gathering evidence... looking for your feedback @manuelgu 
Dependency: `com.github.quanticc:Discord4j:60d8667`

**Proof of testing:** Thanks to Kagumi#1690
Kagumi#1690

**Issues Fixed:** 
- Ready event not firing due to ConcurrentModificationException

### Changes Proposed in this Pull Request
* Use a concurrent collection instead of ArrayList + manual synchronization

### CODE REVIEW

**Comment by manuelgu** [comment]
Looks good 👍

**Comment by austinv11** [comment]
Why use that KeySet instead of a CopyOnWriteArrayList or a similar concurrent list implementation?

**Comment by ArsenArsen** [comment]
RandomAccess isn't needed, plus https://stackoverflow.com/questions/17853112/in-what-situations-is-the-copyonwritearraylist-suitable  This is also a hashCode based implementation making it even more performant.

**Comment by quanticc** [comment]
List is not needed (no usage of random access), it's just a simple collection that dies fairly quickly, we just need it to be concurrent. That leaves only 2 options (in my opinion): ConcurrentHashMap (set view) and ConcurrentSkipListSet. Pick your poison there..

**Comment by austinv11** [comment]
Sounds good

**Pull request merged**
